"""
Extract the injected T2 section from Freighter's patched.dol and emit a Go
source file (internal/inject/blob.go) that the standalone `ww.exe patch`
subcommand uses to splice the same delta into a user's vanilla Wind Waker
ISO. Run after `inject/build.py` produces a fresh patched.dol.

Outputs the T2 bytes ONLY (the new code section). The OSInit patches are
fixed constants encoded in inject/dol.go; the Freighter clobber-reverts
that build.py performs are skipped here because for the standalone
patcher we never apply the clobbers in the first place.

The user's vanilla DOL is the source of all "original game code" bytes;
nothing copyrighted ships in our binary.
"""

import os
import struct
import sys
import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ORIG = os.path.join(ROOT, "inject", "original.dol")
PATCHED = os.path.join(ROOT, "inject", "patched.dol")
OUT = os.path.join(ROOT, "internal", "inject", "blob.go")


def main():
    if not os.path.exists(ORIG):
        print(f"ERROR: {ORIG} not found", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(PATCHED):
        print(f"ERROR: {PATCHED} not found — run inject/build.py first", file=sys.stderr)
        sys.exit(1)

    with open(ORIG, "rb") as f:
        orig = f.read()
    with open(PATCHED, "rb") as f:
        patched = f.read()

    if len(patched) <= len(orig):
        print(f"ERROR: patched ({len(patched)}) not larger than original ({len(orig)})",
              file=sys.stderr)
        sys.exit(1)

    blob = patched[len(orig):]

    # Read T2 section metadata from patched DOL header.
    text_off = struct.unpack(">7I", patched[0x00:0x1C])
    text_addr = struct.unpack(">7I", patched[0x48:0x64])
    text_size = struct.unpack(">7I", patched[0x90:0xAC])

    # T2 is the slot Freighter chose. Verify and extract.
    t2_idx = 2
    if (text_off[t2_idx] != len(orig) or
            text_size[t2_idx] != len(blob)):
        print(f"ERROR: T2 section header doesn't match appended bytes:", file=sys.stderr)
        print(f"  T2 file_off=0x{text_off[t2_idx]:x} size=0x{text_size[t2_idx]:x}", file=sys.stderr)
        print(f"  appended at=0x{len(orig):x} len=0x{len(blob):x}", file=sys.stderr)
        sys.exit(1)

    t2_address = text_addr[t2_idx]
    t2_size = text_size[t2_idx]

    # Diff orig vs patched within the original DOL's footprint to find every
    # in-DOL byte modification. These are the OSInit immediate patches that
    # build.py applies post-Freighter, plus any future direct edits. Excludes
    # the appended T2 section (handled separately) and the DOL header changes
    # (the standalone patcher rebuilds those from scratch).
    HEADER_END = 0x100
    patch_runs = []  # list of (file_off, bytes)
    i = HEADER_END
    n = len(orig)
    while i < n:
        if patched[i] != orig[i]:
            j = i
            while j < n and patched[j] != orig[j]:
                j += 1
            patch_runs.append((i, patched[i:j]))
            i = j
        else:
            i += 1

    print(f"Extracted T2 blob:")
    print(f"  size:    0x{t2_size:x} ({t2_size} bytes)")
    print(f"  address: 0x{t2_address:08x}")
    print(f"In-DOL patches: {len(patch_runs)} run(s)")
    for off, b in patch_runs:
        print(f"  @ 0x{off:08x}  {len(b)}B  {b.hex()}")
    print(f"  output:  {OUT}")

    # Emit blob.go.
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    lines = []
    lines.append("// Code generated by scripts/extract_blob.py - DO NOT EDIT.")
    lines.append(f"// Source: inject/patched.dol minus inject/original.dol.")
    lines.append(f"// Built:  {datetime.datetime.now(datetime.UTC).isoformat(timespec='seconds').replace('+00:00', 'Z')}")
    lines.append("")
    lines.append("package inject")
    lines.append("")
    lines.append("// T2Address is where the appended section lives in MEM1 once the")
    lines.append("// patched DOL is loaded by Dolphin's apploader emulation. Must match")
    lines.append("// the inject_address Freighter was configured with in inject/build.py.")
    lines.append(f"const T2Address uint32 = 0x{t2_address:08X}")
    lines.append("")
    lines.append("// T2Bytes is the full content of the new text section. Splicing it")
    lines.append("// into a user's vanilla DOL means: pick the first unused text-section")
    lines.append("// slot in the DOL header, set its file_offset = old_dol_size,")
    lines.append("// mem_addr = T2Address, size = len(T2Bytes), then append the bytes")
    lines.append("// to the end of the DOL. See internal/inject/dol.go.")
    lines.append("var T2Bytes = []byte{")

    # 16 bytes per line.
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"\t{hex_bytes},")

    lines.append("}")
    lines.append("")

    # In-DOL patch records (currently the OSInit arena-lo immediate writes
    # that point __OSArenaLo past the mailbox). Captured by diffing
    # original vs patched within the original DOL's footprint, so any
    # future direct game-code edit Freighter applies will be picked up
    # automatically without changing this script.
    lines.append("// DOLPatch is a single contiguous byte run to write into the user's")
    lines.append("// vanilla DOL at FileOff. Used by inject/dol.go.")
    lines.append("type DOLPatch struct {")
    lines.append("\tFileOff uint32")
    lines.append("\tBytes   []byte")
    lines.append("}")
    lines.append("")
    lines.append("// DOLPatches captures every in-DOL byte modification Freighter +")
    lines.append("// inject/build.py performs on top of the appended T2 section.")
    lines.append("// Today: the four OSInit immediates that bump __OSArenaLo past")
    lines.append("// our T2 + mailbox. Tomorrow: any direct game-code edit added.")
    lines.append("// Auto-extracted via byte-wise diff so this list stays correct.")
    lines.append("var DOLPatches = []DOLPatch{")
    for off, b in patch_runs:
        bs = ", ".join(f"0x{x:02X}" for x in b)
        lines.append(f"\t{{FileOff: 0x{off:08X}, Bytes: []byte{{{bs}}}}},")
    lines.append("}")
    lines.append("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
